name: Python Cron Job

on:
  schedule:
    # Roda a cada uma hora
    - cron: '10 * * * *'
    # Roda entre 4h e 7h a cada 30 minutos
    - cron: '30 4-7 * * *'
  workflow_dispatch: # Permite executar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name:  Checar repositório
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script # run main.py
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py