name: Python Cron Job

on:
  schedule:
    # Roda a cada uma hora
    - cron: '10 * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checar repositório
        uses: actions/checkout@v2

      - name: Configurar o Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar script
        run: |
          python main.py
